### ISSUE TITLE
How do I test on my own dataset

### ISSUE THREAD

**Issue by pilgrim-powerJ** [mareikethies/geometry_gradients_CT#1]
The projection matrix is constructed using which type of coordinate system?
 How are the world coordinate system and the detector coordinate system established?

**Comment by mareikethies** [comment]
Hi, 
our coordinate system is defined equivalently to the one used in [PyroNN](https://github.com/csyben/PYRO-NN/tree/master). You can check [here](https://github.com/csyben/PYRO-NN/blob/master/pyronn/ct_reconstruction/helpers/trajectories/circular_trajectory.py) (3d example) to check how to construct a set of cone-beam projection matrices for a circular trajectory using basic parameters such as number of projections, source to detector distance, detector spacing etc. Does that help?
What is the geometry format that you currently have for your custom data set?

**Comment by pilgrim-powerJ** [comment]
Thank you for your valuable information and guidance.
